/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria a conta (exige o código de convite) e devolve a sessão */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica e devolve uma nova sessão */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoga a sessão atual */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário autenticado */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Viagens das quais sou membro (mais recentes primeiro) */
        get: operations["listTrips"];
        put?: never;
        /** Cria uma viagem; quem cria vira OWNER */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /** Detalhes da viagem */
        get: operations["getTrip"];
        put?: never;
        post?: never;
        /** Remove a viagem (somente OWNER; soft delete) */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        /** Atualização parcial (OWNER e ADMIN). Exige a versão que o cliente viu */
        patch: operations["updateTrip"];
        trace?: never;
    };
    "/api/v1/trips/{tripId}/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passa a posse para outro membro (somente OWNER); o dono anterior vira ADMIN */
        post: operations["transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /** Membros da viagem (OWNER primeiro), com o que eu posso fazer com cada um */
        get: operations["listMembers"];
        put?: never;
        /** Adiciona um membro pelo email (OWNER e ADMIN) */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{tripId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove um membro, ou sai da viagem quando `userId` é o meu */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Muda o papel de um membro */
        patch: operations["changeMemberRole"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Código estável do erro; use-o para traduzir a mensagem.
         * @enum {string}
         */
        ErrorCode: "route_not_found" | "malformed_json" | "body_too_large" | "invalid_id" | "unauthenticated" | "invalid_token" | "invalid_credentials" | "invalid_registration_code" | "email_taken" | "validation_failed" | "rate_limited" | "internal_error" | "user_not_found" | "trip_not_found" | "trip_id_taken" | "version_conflict" | "empty_patch" | "forbidden" | "member_exists" | "member_not_found" | "owner_locked" | "owner_assignment" | "already_owner";
        Problem: {
            status: number;
            title: string;
            code: components["schemas"]["ErrorCode"];
            /** @description Mensagem em inglês, segura para exibir como fallback. */
            detail: string;
            /** @description Identificador para suporte; o mesmo vai no header X-Request-ID. */
            requestId?: string;
            /** @description Presente em erros de validação (422). */
            errors?: {
                field: string;
                message: string;
            }[];
        };
        /** @enum {string} */
        Role: "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";
        /**
         * @description Papéis que podem ser atribuídos diretamente. OWNER só muda por transfer-ownership.
         * @enum {string}
         */
        AssignableRole: "ADMIN" | "MEMBER" | "VIEWER";
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        Session: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["User"];
        };
        RegisterRequest: {
            email: string;
            name: string;
            password: string;
            registrationCode: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description O que o usuário pode fazer nesta viagem. Calculado pelo servidor; a UI só lê. */
        TripCapabilities: {
            updateTrip: boolean;
            manageMembers: boolean;
            writeContent: boolean;
            deleteTrip: boolean;
            transferOwnership: boolean;
            leave: boolean;
            /** @description Papéis que o usuário pode atribuir ao adicionar um membro. */
            addableRoles: components["schemas"]["AssignableRole"][];
        };
        Trip: {
            /** Format: uuid */
            id: string;
            name: string;
            destination: string;
            /**
             * Format: date
             * @description Data civil (YYYY-MM-DD), sem fuso horário.
             */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @description Fuso IANA, por exemplo America/Sao_Paulo. */
            timezone: string;
            /** @description Código ISO 4217. */
            currency: string;
            /** Format: uuid */
            ownerId: string;
            myRole: components["schemas"]["Role"];
            capabilities: components["schemas"]["TripCapabilities"];
            /**
             * Format: int64
             * @description Enviar como baseVersion ao atualizar.
             */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTripRequest: {
            /**
             * Format: uuid
             * @description Opcional. UUID em minúsculas gerado no cliente (criação offline).
             */
            id?: string;
            name: string;
            destination: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            timezone: string;
            currency: string;
        };
        UpdateTripRequest: {
            /**
             * Format: int64
             * @description Versão da viagem que o cliente viu. Se estiver desatualizada, a resposta é 409 version_conflict.
             */
            baseVersion: number;
            name?: string;
            destination?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            timezone?: string;
            currency?: string;
        };
        TransferOwnershipRequest: {
            /** Format: uuid */
            userId: string;
        };
        /** @description O que o usuário atual pode fazer com este membro. */
        MemberCapabilities: {
            assignableRoles: components["schemas"]["AssignableRole"][];
            /** @description Remover o membro, ou sair da viagem quando é o próprio usuário. */
            canRemove: boolean;
        };
        Member: {
            /** Format: uuid */
            userId: string;
            name: string;
            email: string;
            role: components["schemas"]["Role"];
            capabilities: components["schemas"]["MemberCapabilities"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AddMemberRequest: {
            email: string;
            role: components["schemas"]["AssignableRole"];
        };
        ChangeRoleRequest: {
            role: components["schemas"]["AssignableRole"];
        };
    };
    responses: {
        /** @description Sessão criada. */
        Session: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description Requisição malformada (JSON inválido, campo desconhecido, id fora do formato). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Sem autenticação, token inválido ou expirado, ou credenciais inválidas. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Autenticado, mas sem permissão para esta ação. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Recurso inexistente, ou que o usuário não pode saber que existe. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflito de estado (versão desatualizada, email já cadastrado, id já usado, membro já existe). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Dados bem formados que violam uma regra; `errors` lista os campos. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Limite de requisições excedido. */
        TooManyRequests: {
            headers: {
                /** @description Segundos até poder tentar de novo. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        TripId: string;
        UserId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A API está de pé. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: components["responses"]["Session"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão revogada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O usuário da sessão. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de viagens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Trip"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Viagem criada. */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A viagem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Viagem removida. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripRequest"];
            };
        };
        responses: {
            /** @description Viagem atualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    transferOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnershipRequest"];
            };
        };
        responses: {
            /** @description A viagem, já com o novo dono e o meu novo papel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de membros. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Member"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Membro adicionado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membro removido. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    changeMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description Membro atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
}
